/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisitasRouteImport } from './routes/visitas'
import { Route as FilaRouteImport } from './routes/fila'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrcamentosIndexRouteImport } from './routes/orcamentos.index'
import { Route as OrcamentosFolderIdRouteImport } from './routes/orcamentos.$folderId'

const VisitasRoute = VisitasRouteImport.update({
  id: '/visitas',
  path: '/visitas',
  getParentRoute: () => rootRouteImport,
} as any)
const FilaRoute = FilaRouteImport.update({
  id: '/fila',
  path: '/fila',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentosIndexRoute = OrcamentosIndexRouteImport.update({
  id: '/orcamentos/',
  path: '/orcamentos/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentosFolderIdRoute = OrcamentosFolderIdRouteImport.update({
  id: '/orcamentos/$folderId',
  path: '/orcamentos/$folderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fila': typeof FilaRoute
  '/visitas': typeof VisitasRoute
  '/orcamentos/$folderId': typeof OrcamentosFolderIdRoute
  '/orcamentos/': typeof OrcamentosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fila': typeof FilaRoute
  '/visitas': typeof VisitasRoute
  '/orcamentos/$folderId': typeof OrcamentosFolderIdRoute
  '/orcamentos': typeof OrcamentosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fila': typeof FilaRoute
  '/visitas': typeof VisitasRoute
  '/orcamentos/$folderId': typeof OrcamentosFolderIdRoute
  '/orcamentos/': typeof OrcamentosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fila'
    | '/visitas'
    | '/orcamentos/$folderId'
    | '/orcamentos/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fila' | '/visitas' | '/orcamentos/$folderId' | '/orcamentos'
  id:
    | '__root__'
    | '/'
    | '/fila'
    | '/visitas'
    | '/orcamentos/$folderId'
    | '/orcamentos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FilaRoute: typeof FilaRoute
  VisitasRoute: typeof VisitasRoute
  OrcamentosFolderIdRoute: typeof OrcamentosFolderIdRoute
  OrcamentosIndexRoute: typeof OrcamentosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visitas': {
      id: '/visitas'
      path: '/visitas'
      fullPath: '/visitas'
      preLoaderRoute: typeof VisitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fila': {
      id: '/fila'
      path: '/fila'
      fullPath: '/fila'
      preLoaderRoute: typeof FilaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamentos/': {
      id: '/orcamentos/'
      path: '/orcamentos'
      fullPath: '/orcamentos/'
      preLoaderRoute: typeof OrcamentosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamentos/$folderId': {
      id: '/orcamentos/$folderId'
      path: '/orcamentos/$folderId'
      fullPath: '/orcamentos/$folderId'
      preLoaderRoute: typeof OrcamentosFolderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FilaRoute: FilaRoute,
  VisitasRoute: VisitasRoute,
  OrcamentosFolderIdRoute: OrcamentosFolderIdRoute,
  OrcamentosIndexRoute: OrcamentosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
